### ISSUE TITLE
trackWidth as a prop

### ISSUE THREAD

**Issue by sandeepk9635** [mnkhouri/react-circular-slider#11]
Can we have the trackWidth as a prop, i see that you use trackWidth as 4 now. Btw thankyou for this great tool !!

**Comment by monecchi** [comment]
Check out this **[fork](https://github.com/sounderfm/react-circular-slider/compare/master...tkdamian:master)**, it has been added the `trackWidth` prop as also **touchEvents** support, as it seems not to work on iOS / touch devices...

I've forked it too as I want to implement color gradient support. The component itself already does a great job, (thanks to @mnkhouri!) However, I feel it just needs some room for further customization.

**Comment by mnkhouri** [comment]
Thanks for the pointer, glad to see someone else has this implemented!

**Comment by khazifire** [comment]
![image](https://github.com/mnkhouri/react-circular-slider/assets/73513866/53f9e9a9-e1d0-44bd-a6e9-8ada621d62d0)
@sandeepk9635  @monecchi i was able to increase the trackWith by overriding the path stroke width

```css
#mycontainer >svg>path{
  stroke-width: 20px !important;
  stroke: #5abc9a;
}
 
#mycontainer > svg > path:first-child {
  stroke-width: 20px !important;
  stroke: #F1F3F5;
}
```
